const categories = {
  vegetables: [
    "acorn squash", "artichoke", "arugula", "asparagus", "avocado", "baby bella mushroom", 
    "beet", "beet green", "bell pepper", "black bean", "black eyed pea", "broccoli", 
    "broccolini", "brussels sprout", "butternut squash", "cabbage", "carrot", "cauliflower", 
    "celery", "collard green", "corn", "cucumber", "eggplant", "green bean", "green cabbage", 
    "green chiles", "green onion", "green peanut", "green pepper", "jalapeno", "jalapeno pepper", 
    "jalapeño pepper", "kale", "kale green", "lettuce", "mushroom", "okra", "onion", "pea", 
    "pepper", "potato", "pumpkin", "radishes", "red cabbage", "red chili pepper", "red onion", 
    "red pepper", "red potato", "snap pea", "snow pea", "spinach", "squash", "stalk asparagus", 
    "stalk celery", "sweet potato", "tomatillo", "tomato", "turnip", "yukon gold potato", 
    "zucchini"
  ],
  fruits: [
    "apple", "banana", "blackberry", "blueberry", "cherry", "cranberry", "date", "fig", 
    "grape", "grapefruit", "kiwi", "lemon", "lime", "mango", "nectarine", "orange", "peach", 
    "pear", "pineapple", "pomegranate", "raspberry", "strawberry", "watermelon"
  ],
  dairy: [
    "american cheese", "blue cheese", "boursin", "brie", "butter", "buttermilk", "cheddar cheese", 
    "cheese", "cream", "cream cheese", "feta cheese", "goat cheese", "greek yogurt", "ice cream", 
    "milk", "mozzarella cheese", "parmesan cheese", "ricotta cheese", "sour cream", "swiss cheese", 
    "whipping cream", "yogurt", "boursin cheese", "burrata cheese", "cheddar biscuit", 
    "cheese ravioli", "cheese tortellini", "cream biscuit", "cream topping", "cream style corn", 
    "mexican blend cheese", "monterey jack cheese", "neufchatel cheese", "provolone cheese", 
    "queso", "queso cheese", "ricotta cheese"
  ],
  spices: [
    "adobo sauce", "allspice", "basil", "bay leaves", "black pepper", "cayenne pepper", 
    "celery salt", "cinnamon", "cloves", "cumin", "curry powder", "dill", "garlic powder", 
    "ginger", "ginger root", "nutmeg", "oregano", "paprika", "parsley", "rosemary", "sage", 
    "salt", "sea salt", "thyme", "vanilla extract", "vanilla bean"
  ],
  meat: [
    "bacon", "beef", "canadian bacon", "chicken", "deli ham", "italian sausage", "lamb", "pork", 
    "prosciutto", "sausage", "turkey", "andouille sausage", "brisket", "chuck", "ham", "ham hock", 
    "hanger steak", "meatball", "neck turkey", "prime rib", "rib", "ribeye steak", "salmon", 
    "salmon fillet", "salmon steak", "sirloin", "skirt steak", "steak", "venison"
  ],
  seafood: [
    "anchovy paste", "crab", "crawfish", "fish", "lobster tail", "sea scallops", "shrimp", 
    "tilapia", "tilapia filet", "tuna", "water tuna"
  ],
  grains: [
    "bagel", "baguette", "bread", "bread crumb", "brown rice", "biscuit", "cornbread", "flour", 
    "granola", "oat", "oatmeal", "pasta", "quinoa", "rice", "tortilla", "angel food cake", 
    "baking apple", "baking powder", "baking soda", "bowtie pasta", "brown butter", 
    "brown sugar", "buttermilk biscuit", "buttermilk cornbread", "buttermilk cornmeal", 
    "buttermilk pancake", "buttermilk ranch dressing", "butterscotch chip", "buttery cracker", 
    "buttermilk biscuit", "caesar dressing", "caesar salad dressing", "cake", "candy", "cane sugar", 
    "canellini", "cheddar biscuit", "chocolate cake", "cooking oil", "cooking spray", "croissant", 
    "crouton", "crumb", "crisco", "cuban bread", "french bread", "frito corn chip", "gelatin", 
    "jello", "jelly", "juice", "macadamia nut", "marshmallow", "marshmallow cream", 
    "marshmallow fluff", "marzipan", "meringue", "milk chocolate", "milk chocolate bar", 
    "milk powder", "miniature marshmallow", "miniature peanut butter", "miniature phyllo shell", 
    "muffin", "naan bread", "navel orange", "navy bean", "neck turkey", "nectarine", "neufchatel cheese", 
    "nonpareil", "nut", "nut butter", "nutella", "oatmeal raisin cookie", "oil", "olive oil", 
    "pasta sauce", "pea", "penne pasta", "pretzel", "puff pastry", "pasta", "pastry", "pie crust", 
    "pita bread", "pizza dough", "pizza sauce", "poppy seed", "popcorn", "queso", "queso cheese", 
    "quinoa", "rainbow sprinkles", "raisin", "rapid rise", "rice", "rice cereal", "rice krispies cereal", 
    "rice wine vinegar", "ritz cracker", "rotel tomato", "russet", "sandwich bread", "seasonal vegetable", 
    "self rising cornmeal", "self rising flour", "sesame oil", "sesame seed", "shallot", 
    "shortbread cookie", "shortbread crust", "shortening", "skewer", "sleeve ritz cracker", 
    "sleeve saltine cracker", "sourdough", "sourdough bread", "southern buttermilk biscuit", 
    "southern buttermilk cornbread", "southern pimento cheese", "southern praline", "spaghetti", 
    "sugar", "sugar cookie", "sugar eyeball", "sugar for rolling", "sugar snap pea", 
    "sunflower seed", "taco seasoning", "tortellini", "vanilla buttercream", "vanilla cake", 
    "vanilla cook", "vanilla wafer", "wheat", "wheat bread", "wheel brie cheese", "yeast", "yogurt", 
    "ziti noodle"
  ],
  sauces: [
    "balsamic beef", "balsamic dressing", "balsamic glaze", "balsamic vinaigrette", 
    "barbeque sauce", "bbq sauce", "balsamic vinegar", "chimichurri sauce", "chocolate buttercream", 
    "chocolate ganache", "chocolate ganache cracer", "chocolate sauce", "chocolate syrup", 
    "cranberry sauce", "espresso", "fudge icing", "garnish", "garnish basil leaves", 
    "giblet", "gorgonzola cheese", "gochujang", "gochujang sauce", "grand marnier", 
    "gravy", "gravy balsamic beef", "guacamole", "horseradish", "horseradish sauce", "jasmine rice", 
    "jelly", "juice lemon", "karo syrup", "ketchup", "key lime juice", "key lime zest", "lime", 
    "magic shell", "maple syrup", "maraschino cherry", "marinara", "marinara sauce", 
    "marsala wine", "mascarpone", "milk greek yogurt", "molasses", "mustard", "mustard spice", 
    "organic honey", "pepper jelly", "pesto", "pico de gallo", "pimento", "pine nut", "pineapple", 
    "pineapple juice", "poblano pepper", "pomegranate", "raspberry sauce", "raspberry vinaigrette", 
    "red velvet cake cupcake", "red wine", "red wine vinaigrette", "red wine vinegar", "relish", 
    "root beer", "rosemary ranch dressing", "rotel tomato", "salt", "sauce", "seasoning", 
    "serve pudding", "siracha sauce", "siracha", "sour cream", "splash balsamic vinegar", 
    "sprig chives", "sprig mint leaves", "sprig rosemary", "sprig thyme", "sprinkle sea salt", 
    "sprinkles", "stone mustard", "stone house seasoning", "stone grit", "syrup", "tabasco", 
    "tabasco sauce", "tartar", "teriyaki sauce", "tzatziki sauce", "vanilla extract", "vinaigrette", 
    "vinegar", "worcestershire sauce"
  ],
  others: [
    "almond", "almond flour", "apple cider", "apple cider vinegar", "apple juice", "apple pie spice", 
    "apple sauce", "baking soda", "bean", "biscuit", "bittersweet chocolate", "black olive", 
    "bone", "boston", "bowtie pasta", "broth", "canellini", "canola", "caramel", "carrot", "catfist", 
    "celery seed", "champagne vinegar", "chia seed", "chili", "chili bean", "chili powder", 
    "chipotle chili", "chipotle pepper", "chives", "chocolate", "chocolate chip", 
    "chocolate chip morsel", "chocolate cookie", "chocolate graham cracker", "chocolate sandwich cookie", 
    "chocolate wafer", "chorizo", "chow mein noodle", "clear jel", "clear vanilla extract", "coca cola", 
    "cocktail weenie", "cocoa", "coconut", "coconut cream", "coconut extract", "coconut milk", 
    "coconut oil", "coffee", "coke", "coleslaw", "condensed celery soup", "condensed chicken soup", 
    "condensed milk", "confectioner sugar", "cookie", "corn kernel", "corn meal", "corn starch", 
    "corn syrup", "cornish hen", "cranberry juice", "cranberry juice cocktail", "crisco", 
    "crouton", "crush peppermint candy", "cuban bread", "cube steak", "dark", "dark brown sugar", 
    "dark chocolate", "dark chocolate chip", "dark chocolate espresso bit", "dark cocoa powder", 
    "dark rum", "day donut", "decorator", "dijon mustard", "dill pickle", "dinner", "ditalini pasta", 
    "double crust pie dough", "dr pepper", "dripping", "ear corn", "egg", "egg noodle", 
    "elbow macaroni noodle", "elbow noodle", "elbow pasta", "enchilada sauce", "farfalle pasta", 
    "fennel seed", "fettucine", "filet tilapia", "fingerling potato", "flake coconut", "flaky fish", 
    "flank", "flour tortilla", "food color", "food coloring", "fruit", "fudge brownies", "garlic", 
    "ginger root", "grain dijon mustard", "grain mustard", "granny smith apple", "great northern bean", 
    "green chiles", "green food coloring", "green olive", "green onion", "grit", "guacamole", 
    "hemp heart", "herb", "hershey kiss", "hoagie", "hollandaise sauce", "hominy", "honey", 
    "honey butter", "honey cinnamon cookie", "honey mustard dressing", "ice", "ice cream cone", 
    "ice water", "iceberg lettuce", "icing", "individual stalk celery", "instant espresso", 
    "instant pot potato", "instant yeast", "italian dressing", "italian seasoning", "jasmine rice", 
    "jello", "juice", "kalamata olive", "kale green", "kernel corn", "key lime", "key lime zest", 
    "kosher salt", "lasagna noodle", "lemonade", "lightly brown sugar", "lime", "linguine", 
    "lollipop", "macadamia nut", "magic shell", "mahi mahi", "mandarin orange", "maple flavoring", 
    "maraschino cherry", "marsala wine", "melting chip", "miniature peanut butter", "mint", 
    "mint leaves", "molasses", "nonpareil", "nut", "nut butter", "nutella", "oat", "okra pod", 
    "olive", "onion powder", "orange juice", "orange rind", "orange zest", "oreo cookie", 
    "organic chicken", "oyster cracker", "panko", "parsley leaves", "peach jelly", "peach preserves", 
    "peanut", "peanut butter", "peanut oil", "peanut sauce", "pearl onion", "pecan", "penne pasta", 
    "pepper jack cheese", "pepperoncini pepper", "pepperoni", "pickle", "pico de gallo", 
    "pine nut", "pinto bean", "pistachio", "pita bread", "poblano pepper", "popcorn", "poppy seed", 
    "pork sparerib", "portion turkey", "portobello", "potato", "pototo", "poultry season", 
    "pretzel", "root beer", "rotel tomato", "russet", "sage", "salad", "salad dressing", 
    "salad green", "seafood", "self rising cornmeal", "self rising flour", "semi chocolate chip", 
    "sesame oil", "shallot", "shell pasta", "shortbread cookie", "shortbread crust", "shortening", 
    "simple syrup", "size squash", "skillet", "skirt steak", "sleeve ritz cracker", 
    "sleeve saltine cracker", "soju", "sodium soy sauce", "southern praline", "spicy brown sugar rub", 
    "spicy mustard barbeque sauce", "spicy rub", "strawberry buttercream", "strawberry fruit", 
    "strawberry jello", "strawberry muffin", "strawberry syrup", "streusel", "sub sandwich", 
    "sugar cookie", "sunflower seed", "texas toast", "tilapia filet", "toffee bit", "toothpick", 
    "topping", "turbinado sugar", "turkey sausage", "turkey stock", "vanilla ice cream", 
    "vanilla pudding", "vegetable", "vegetable broth", "vegetable oil", "velveeta cheese", 
    "water", "well", "wheat", "wonton wrapper", "yogurt"
  ]
};

module.exports = categories;
