const categories = {
    vegetables: [
      "acorn squash", "artichoke", "artichoke heart", "arugula", "asparagus",
      "asparagus spear", "avocado", "avocado puree", "baby bella mushroom",
      "basil", "basil leaves", "beet", "beet green", "bell pepper", "black bean",
      "black eyed pea", "broccoli", "broccoli floret", "broccoli slaw",
      "broccolini", "brussels sprout", "cabbage", "carrot", "cauliflower",
      "celery", "celery leaves", "cherry tomato", "chickpea", "chili", "chili bean",
      "chili pepper", "chipotle chili", "chipotle pepper", "collard green",
      "collard green leaves", "corn", "cucumber", "eggplant", "green bean",
      "green chiles", "green onion", "green pepper", "jalapeno", "jalapeno pepper",
      "jalapeño", "jalapeño pepper", "kale", "kale green", "lettuce", "lettuce green",
      "lettuce leaves", "mushroom", "okra", "onion", "pea", "pepper",
      "poblano pepper", "potato", "pumpkin", "radish", "red onion", "red pepper",
      "romaine lettuce", "shallot", "snap pea", "spinach", "squash", "tomatillos",
      "tomato", "zucchini", "zucchini squash"
    ],
    fruits: [
      "apple", "apricot", "avocado", "banana", "blackberry", "blueberry", "cherry",
      "coconut", "cranberry", "date", "fig", "grapefruit", "grape", "kiwi", "lemon",
      "lime", "mango", "melon", "nectarine", "orange", "papaya", "peach", "pear",
      "pineapple", "plum", "pomegranate", "raspberry", "strawberry", "tangerine",
      "watermelon"
    ],
    dairy: [
      "butter", "cheese", "cream", "cream cheese", "milk", "sour cream", "yogurt",
      "whipped cream", "ice cream", "brie", "boursin", "blue cheese", 
      "blue cheese crumble", "blue cheese dressing", "cheddar cheese", 
      "cheese ravioli", "cheese tortellini", "cream cheese frosting", "feta cheese", 
      "goat cheese", "greek yogurt", "gorgonzola cheese", "gorgonzola cheese crumble", 
      "mozzarella", "neufchatel cheese", "parmesan", "parmesan cheese", 
      "pepper jack cheese", "provolone cheese", "ricotta cheese", "swiss cheese", 
      "queso", "velveeta cheese"
    ],
    spices: [
      "allspice", "basil", "bay leaves", "black pepper", "cayenne pepper", 
      "chili powder", "cinnamon", "cloves", "cumin", "dill", "garlic powder", 
      "ginger", "nutmeg", "oregano", "paprika", "parsley", "pepper", "rosemary", 
      "sage", "thyme", "garlic", "clove garlic", "cloves garlic", "jalapenos", 
      "mint", "cilantro", "coriander", "turmeric", "fennel seed", "mustard", 
      "curry powder", "chipotle pepper", "chives", "parsley leaves", 
      "poultry season", "italian seasoning"
    ],
    meat: [
      "bacon", "beef", "beef bouillon", "beef brisket", "beef broth", "beef stock", 
      "beef tenderloin", "chicken", "chicken leg", "chicken marinade", "chicken soup", 
      "chicken stock", "chicken tender", "chicken tenderloin", "chicken thigh", 
      "chicken wing", "duck", "ham", "lamb", "pork", "salami", "sausage", "turkey", 
      "veal", "pork chop", "pork loin", "pork roast", "pork shoulder", "pork sirloin", 
      "pork sparerib", "pork tenderloin", "prosciutto", "rib", "ribeye steak", 
      "venison roast", "venison tenderloin", "meatball", "brisket", "andouille sausage", 
      "breakfast sausage", "italian sausage", "pork butt", "pork sirloin"
    ],
    seafood: [
      "catfish", "clam", "crab", "lobster", "mackerel", "mussel", "oyster", "salmon", 
      "sardine", "scallop", "shrimp", "snapper", "tilapia", "trout", "tuna", 
      "anchovy paste", "catfish filet", "filet tilapia", "flaky white fish", 
      "mahi mahi", "salmon steak", "seafood"
    ],
    grains: [
      "barley", "buckwheat", "bulgur", "cornmeal", "couscous", "farro", "millet", 
      "oats", "quinoa", "rice", "sorghum", "spelt", "wheat", "wild rice", "bread", 
      "bread crumb", "flour", "flour tortilla", "wholemeal flour", "wonton wrapper", 
      "graham cracker", "graham cracker crumb", "graham cracker crust", "biscuit", 
      "bagel", "baguette", "croissant", "english muffin", "cracker", "cracker crumb", 
      "pita bread", "sub sandwich", "sandwich bread", "hamburger bun", "hoagie", 
      "cuban bread", "french bread", "dinner roll", "deli roll", "pretzel", 
      "pretzel twist", "shortbread", "shortbread cookie", "shortbread crust", 
      "shortbread pie crust", "naan", "naan bread", "cornbread", "cornbread mix", 
      "crescent", "bun", "cookie", "cookie dough", "pie crust", "puff pastry", 
      "sourdough bread"
    ],
    other: [
      "adobo sauce", "agave", "air fryer potato", "almond", 
      "almond extract", "almond flour", "apple cider", "apple cider concentrate", 
      "apple cider vinegar", "apple juice", "apple pie spice", "applesauce", 
      "bacon dripping", "bacon jam", 
      "bacon vinaigrette", "bake shortbread cookie", "baking apple", "baking powder", 
      "baking soda", "balsamic dressing", "balsamic glaze", "balsamic roast beef", 
      "balsamic vinaigrette", "balsamic vinegar", "banana", "barbeque sauce", 
      "bean", "beef bouillon", "beef brisket", "beef broth", "beef stock", 
      "beef tenderloin", "bittersweet chocolate", "black bean chili", 
      "black olive", "bone", "boston", 
      "breakfast sausage", "broccoli", "broccoli floret", 
      "broccoli slaw", "broccolini", "broth", "brown butter", "brown rice", 
      "brown sugar", "buffalo sauce", "butter", "butter cracker", "butter lettuce", "butter lettuce leaves", 
      "butterbean", "buttermilk", "buttermilk biscuit", "buttermilk cornbread mix", 
      "buttermilk cornmeal", "buttermilk pancake", "buttermilk ranch dressing", 
      "butternut squash", "butterscotch chip", "buttery cracker", "button mushroom", 
      "caesar dressing", "caesar salad dressing", "cajun spice mix", "canadian bacon", 
      "candy", "candy cane", "candy corn", "candy melt", "candy pumpkins", 
      "cane sugar", "canellini", "canola oil", "caramel", "caramel candy", 
      "caramel sauce", "cashew", "catfish filet", 
      "cauliflower", "cayenne pepper", "celery salt", "celery seed", 
      "champagne vinegar", "cheddar biscuit", 
      "cheese tortellini", "cherry pie filling", "cherry sauce", "chewy chocolate chip cookie", 
      "chewy ginger molasses cookie", "chia seed", "chicken tender", "chicken thigh", "chicken wing", 
      "chickpea", "chili powder", "chili sauce", "chimichurri sauce", 
      "chocolate", "chocolate bar", "chocolate buttercream frosting", "chocolate cake", 
      "chocolate candy", "chocolate chip", "chocolate chip chocolate bar", 
      "chocolate chunks", "chocolate ganache", "chocolate ganache filling", 
      "chocolate graham cracker", "chocolate graham cracker crumb", "chocolate ice cream", 
      "chocolate kiss candy", "chocolate sandwich cookie", "chocolate sauce", 
      "chocolate sugar cookie", "chocolate syrup", "chocolate wafer cookie", 
      "chorizo", "chow mein noodle", "chuck", "chuck roast", "citru vinaigrette", 
      "clear jel", "clear vanilla extract", "clove garlic", "cloves garlic", 
      "coarse sugar", "coarsely cheddar cheese", "coating cranberry", "coca cola", 
      "coca cola bbq sauce", "cocktail peanut", "cocktail sausage", "cocktail weenie", 
      "cocoa mix", "cocoa powder", "coconut", "coconut amino", "coconut cream", 
      "coconut extract", "coconut flake", "coconut milk", "coconut oil", "coffee", 
      "coke", "cold butter", "cold coffee", "cold heavy whipping cream", "cold water", 
      "coleslaw", "coleslaw mix", "collard green leaves", "condensed celery soup", 
      "condensed chicken soup", "condensed milk", "condensed milk store bought", 
      "confectioner sugar", "cookie dough dip", "cookie icing", "cooking oil", 
      "cool whip", "corn kernel", "corn kernel niblet corn", "corn meal", 
      "corn starch", "corn syrup", "cornbread mix", "cornish hen", "cornmeal mix", 
      "cornstarch", "country ham", "crab boil", "crab meat", "cracker crumb", 
      "cranberry cranberry", "cranberry juice", "cranberry juice cocktail", 
      "cranberry sauce", "crawfish", "cream biscuit", "cream cheese frosting", 
      "cream style white corn", "cream topping", "crescent", "crisco", 
      "crispy bacon bit", "crispy onion", "crispy rice cereal", "crouton", 
      "crush peppermint candy", "cuban bread", "cube steak", "cumin", "dark brown sugar", 
      "dark chocolate", "dark chocolate bar", "dark chocolate chip", "dark chocolate chunks", 
      "dark chocolate espresso bit", "dark cocoa powder", "dark rum", 
      "day donut", "decorator frosting", "deli ham", "deviled egg", "dijon mustard", 
      "dijon mustard powder", "dill pickle", "ditalini pasta", "double crust pie dough", 
      "dr pepper", "dripping", "each tortellini tortellini", "ear corn", "egg", 
      "egg noodle", "egg white", "egg yolk", "elbow macaroni noodle", 
      "elbow noodle", "elbow pasta", "enchilada sauce", "english cucumber", 
      "english pea", "espresso", "espresso powder", "farfalle pasta", "fennel seed", 
      "fettuccine", "fettucine", "fingerling potato", "firmly brown sugar", "flake coconut", 
      "flank", "flank steak", "flour tortilla", "food color", "food coloring", 
      "french bread", "freshly parmesan", "freshly parmesan cheese", "freshly parsley", 
      "freshly peppercorns", "frito corn chip", "fruit", "fudge brownies", 
      "fudge icing", "full ham", "full southern buttermilk cornbread", "garnish", 
      "garnish basil leaves", "giblet", "ginger root", "gochujang", "grain dijon mustard", 
      "grain mustard", "grand marnier", "granny smith apple", "grape jelly", 
      "gravy balsamic roast beef", "great northern bean", "green cabbage", 
      "green food coloring", "green olive", "green peanut", "green tomato", 
      "green tomatoes", "grit", "gruyere cheese", "gruyère cheese", "guacamole", 
      "ham bone", "ham hock", "hanger steak", "head broccoli", "head cabbage", 
      "head cauliflower", "head iceberg lettuce", "head lettuce", "head red cabbage", 
      "head romaine lettuce", "heaping cocoa powder", "heaping mayonnaise", 
      "heavy cream", "heavy whipping cream", "hemp heart", "herb", "hershey kiss", 
      "hoagie", "hollandaise sauce", "hominy", "honey", "honey butter", 
      "honey cinnamon cookie", "honey mustard dressing", "horseradish", 
      "horseradish sauce", "ice", "ice cream cone", "ice water", "icing", 
      "individual stalk celery", "instant espresso", "instant pot potato", 
      "instant yeast", "italian dressing", "jalapeno", "jalapeno pepper", 
      "jalapenos", "jalapeño", "jalapeño pepper", "jasmine rice", "jello", "jelly", 
      "juice", "juice lemon", "kalamata olive", "karo syrup", "kernel corn", 
      "ketchup", "key lime", "key lime juice", "key lime zest", "korean chili pepper powder", 
      "kosher salt", "lasagna noodle", "lemon curd", "lemon juice", "lemon lime soda", 
      "lemon sugar", "lemon zest", "lemonade", "lightly brown sugar", "lima bean", 
      "lima bean lima bean", "lime juice", "lime wedge", "lime zest", "linguine", 
      "lollipop", "macadamia nut", "magic shell", "mandarin orange", "maple flavoring", 
      "maple syrup", "maraschino cherry", "marinara", "marinara sauce", "marsala wine", 
      "marshmallow", "marshmallow cream", "marshmallow creme", "marshmallow fluff", 
      "mayonnaise", "meat dripping", "meringue", "mexican blend cheese", 
      "milk chocolate", "milk chocolate bar", "milk chocolate chip", "milk greek yogurt", 
      "milk powder", "miniature marshmallow", "miniature peanut butter", 
      "miniature phyllo shell", "mint chocolate chip ice cream", "molasses", 
      "monterey jack cheese", "mushroom cream sauce", "mushroom soup", "naan", 
      "naan bread", "navel orange", "navy bean", "neck turkey", "nectarine", 
      "nonpareil", "nonstick cooking spray", "nut", "nut butter", "nutella", 
      "oil", "oil tomato", "okra pod", "olive", "olive oil", "olive oil spray", 
      "onion powder", "orange juice", "orange rind", "orange zest", "oregano flake", 
      "oregano leaves", "oreo cookie", "oreos", "organic chicken", "organic honey", 
      "oyster cracker", "panko", "paprika", "parsley leaves", 
      "pasta sauce", "peach barbeque sauce", "peach bbq sauce", "peach jelly", 
      "peach preserves", "peanut", "peanut butter", "peanut butter chip", 
      "peanut oil", "peanut sauce", "pearl onion", "pecan", "pepper jelly", 
      "peppermint bark", "peppermint candy", "peppermint chocolate chip", 
      "peppermint extract", "pepperoncini pepper", "pepperoni", "pesto", 
      "petite tomato", "pickle", "pico de gallo", "pimento", "pimento cheese", 
      "pimento pepper", "pine nut", "pineapple chunks", "pineapple jalapeno cream cheese", 
      "pineapple juice", "pineapple pineapple", "pineapple pineapple chunks", 
      "pinto bean", "pistachio", "pizza dough", "pizza sauce", "plum tomato", 
      "pomegranate juice", "pomegranate seed", "popcorn", "poppy seed", 
      "poultry season", "pretzel twist", "prime rib", "puff pastry", "pumpkin pie", 
      "pumpkin pie spice", "pumpkin puree", 
      "pure maple syrup", "quinoa", "rainbow sprinkles", "raisin", "ranch dressing", 
      "ranch seasoning", "ranch seasoning mix", "rapid rise", "raspberry preserves", 
      "raspberry sauce", "raspberry vinaigrette", "red apple", "red chili pepper", 
      "red food coloring", "red grape", "red kidney bean", "red pepper cream sauce", 
      "red pepper flake", "red velvet cake cupcake", "red wine", "red wine vinaigrette", 
      "red wine vinegar", "relish", "rib celery", "rice krispies cereal", 
      "rice wine vinegar", "ritz cracker", "roast beef", "roast beef stock", 
      "roast chicken", "roma tomato", "root beer", "rosemary leaves", 
      "rosemary ranch dressing", "rotel tomato", "russet", "russet potato", 
      "salad dressing", "salad green", "salad mix", "salsa", "saltine cracker", 
      "sauteed apple", "scallion", "scant kosher salt", "sea salt", "sea salt flake", 
      "sea scallops", "seasonal vegetable", "seasoning", "self rising cornmeal", 
      "self rising flour", "semi chocolate chip", "serve pudding mix", "sesame oil", 
      "sesame seed", "shell pasta", "shortbread crust", "shortbread pie crust", 
      "shortening", "shrimp", "simple syrup", "siracha sauce", "sirloin", 
      "sirloin steak", "size squash", "skewer", "skillet", "skirt", "skirt steak", 
      "sleeve ritz cracker", "sleeve saltine cracker", "sliced", "snow pea", 
      "sodium soy sauce", "soft oatmeal raisin cookie", "soft pretzel", 
      "soft white bread", "soju", "sour cream", "southern buttermilk biscuit", 
      "southern buttermilk cornbread", "southern caramel icing", 
      "southern pimento cheese", "southern praline", "soy sauce", "spaghetti", 
      "spaghetti noodle", "spaghetti squash", "spicy brown sugar rub", 
      "spicy mustard barbeque sauce", "spicy rub mix", "spinach spinach", 
      "spiral ham", "splash balsamic vinegar", "sprig chives", "sprig mint leaves", 
      "sprig rosemary", "sprig thyme", "spring lettuce mix", "spring salad green", 
      "spring salad green mix", "sprinkle fine sea salt", "sprinkles", "sriracha", 
      "sriracha chili sauce", "sriracha sauce", "stalk asparagus", "stalk celery", 
      "stone grit", "stone house seasoning", "stone mustard", "store bought", 
      "strawberry buttercream", "strawberry buttercream frosting", "strawberry fruit", 
      "strawberry jell o", "strawberry muffin mix", "strawberry syrup", 
      "streusel topping", "strip bacon", "strip bacon dripping", "sub sandwich", 
      "sugar", "sugar cookie", "sugar cookie dough", "sugar eyeball", "sugar for rolling", 
      "sugar snap pea", "sugar sprinkles", "sunflower seed", "syrup", "tabasco", 
      "tabasco sauce", "taco seasoning", "taco seasoning mix", "tahini", "tangerine", 
      "tart apple", "tartar", "teriyaki sauce", "texas toast", "thyme", "tilapia filet", 
      "toffee bit", "tomato paste", "tomato sauce", 
      "tomato vinaigrette", "toothpick", "topping", "tortilla chip", "turbinado sugar", 
      "turkey sausage", "turkey stock", "turnip", "turnip green", "tzatziki sauce", 
      "vanilla bean", "vanilla bean paste", "vanilla buttercream frosting", 
      "vanilla cake", "vanilla cook", "vanilla extract", "vanilla ice cream", 
      "vanilla pudding", "vanilla wafer", "vanilla yogurt", "vegetable broth", 
      "vegetable oil", "vegetable vegetable", "venison roast", "venison tenderloin", 
      "vinaigrette dressing", "vinegar", "violet gel paste food color", 
      "walnut pesto", "warm milk", "warm water", "water", "water tuna", 
      "wheat bread", "wheel brie cheese", "whipping cream cheese", 
      "white american cheese", "white balsamic vinegar", "white bean", "white cake", 
      "white cake mix", "white chocolate buttercream", "white chocolate candy melt melting wafer", 
      "white chocolate chip", "white chocolate chip morsel", "white corn syrup", 
      "white melting chip", "white queso cheese", "white rice", "white sandwich bread", 
      "white vinegar", "white wine", "white wine vinaigrette", "white wine vinegar", 
      "worcestershire sauce", "yellow cake mix", "yellow mustard", "yellow pepper", 
      "yellow squash", "yogurt", "yukon gold potato", "zest", "ziti noodle"
    ]
  };
  
  module.exports = categories;
  